### ISSUE TITLE
Cased Bert?

### ISSUE THREAD

**Issue by dayuyang1999** [castorini/tct_colbert#3]
Hi,

I am wondering Have you ever tried using`bert-base-cased` as the base model? If you tried, does that improve the performance?

By observation, there are a lot of proper nouns in MSMARCO. I am just curious maybe cased-model will have better performance?

Thanks

**Comment by jacklin64** [comment]
Hi @dayuyang1999, thank you for the question. We haven't tried that before but I think your observation is reasonable. We now focus on different types of dense representations, which I think are also able to capture proper nouns better. Here are some our recently developed models in pytorch for your reference https://github.com/castorini/dhr. Hope it is helpful for you. And we've also implement TCT-ColBERT training in pytorch using the above repo and will release a readme for instruction.

**Comment by dayuyang1999** [comment]
> 

Thank you so much for the prompt reply! That is nice work. I am checking it out.
